/**
 * Template Types and Schemas
 *
 * This file defines the TypeScript interfaces for template sections and variables
 * as specified in Story 3.1 Acceptance Criteria #3 and #4
 */

/**
 * Section Type Enum
 * - static: Boilerplate content that doesn't change
 * - ai_generated: Content generated by AI based on prompt guidance
 * - variable: Content with variable placeholders
 */
export type SectionType = 'static' | 'ai_generated' | 'variable';

/**
 * Variable Type Enum
 * Supports text, number, date, and currency types
 */
export type VariableType = 'text' | 'number' | 'date' | 'currency';

/**
 * Template Section Schema (AC #3)
 * Defines the structure of a section within a template
 */
export interface TemplateSection {
  /** Unique identifier for the section */
  id: string;

  /** Display title of the section */
  title: string;

  /** Type of section (static, ai_generated, or variable) */
  type: SectionType;

  /** Static content or content with variable placeholders (null for ai_generated) */
  content: string | null;

  /** Prompt guidance for AI generation (required for ai_generated sections) */
  promptGuidance: string | null;

  /** Whether this section is required in the template */
  required: boolean;

  /** Display order of the section (1-based) */
  order: number;
}

/**
 * Template Variable Schema (AC #4)
 * Defines a variable that can be used in template sections
 */
export interface TemplateVariable {
  /** Variable name (used in placeholders as {{variable_name}}) */
  name: string;

  /** Variable type (text, number, date, currency) */
  type: VariableType;

  /** Whether this variable is required */
  required: boolean;

  /** Default value for the variable (can be null) */
  defaultValue: string | number | null;
}

/**
 * Complete Template Structure
 * This is stored in the JSONB fields of the templates table
 */
export interface TemplateStructure {
  /** Array of sections defining the document structure */
  sections: TemplateSection[];

  /** Array of variables that can be used in sections */
  variables: TemplateVariable[];
}
